### ISSUE TITLE
How to handle cURL error 6: Could not resolve host

### ISSUE THREAD

**Issue by markoman78** [ash-jc-allen/favicon-fetcher#14]
Hi! First of all, thanks for this great package.

I'm building service which handles 500k+ domains and there are many domains that are not available. When this happens, we will get cURL error for "Could not resolve host".

Any suggestions how to handle this error so that we will get favicon as null?

Thanks!

**Comment by ash-jc-allen** [comment]
I'm going to close this for the time being. But, if you're still having the issue and need some help, feel free to reopen it 🙂
