### ISSUE TITLE
Call to a member function cache() on null

### ISSUE THREAD

**Issue by GabrielSieben** [ash-jc-allen/favicon-fetcher#15]
Hello,

If I run the following code which looks like it should work:

```
use AshAllenDesign\FaviconFetcher\Facades\Favicon;
Favicon::fetch("https://example.com/")->cache(now()->addWeek())->getFaviconUrl();
```

It will crash with:
```
[Error] Call to a member function cache() on null
```

**Comment by ash-jc-allen** [comment]
Hey @gjsman!

From what I can see, you should only be getting this with URLs where a favicon can't be fetched properly. Are you also getting this error when trying to grab the favicons from any other URLs? 🙂

**Comment by ash-jc-allen** [comment]
In your particular example, the `fetch` method returns `null` if the favicon can't be found. So, you could potentially update your code to look like so:

```php
Favicon::fetch("https://example.com/")?->cache(now()->addWeek())->getFaviconUrl();
```

Does this help a little bit? 🙂

**Comment by gjsman** [comment]
Huh... that works. Thank you!

**Comment by ash-jc-allen** [comment]
Perfect! I'm glad that it sorted it for you 😄
