### ISSUE TITLE
Exception thrown when link icon tag doesn't have href attribute

### ISSUE THREAD

**Issue by tushargugnani** [ash-jc-allen/favicon-fetcher#74]
`AshAllenDesign\FaviconFetcher\Drivers\HttpDriver::convertToAbsoluteUrl(): Argument #2 ($faviconUrl) must be of type string, null given, called in /Users/tgugnani/Code/thehome/vendor/ashallendesign/favicon-fetcher/src/Drivers/HttpDriver.php on line 189`

When trying to fetch favicon from a URL which does not have a href tag in it, exception is thrown. Can we modify the code so that fails gracefully.

**Comment by ash-jc-allen** [comment]
Hey @tushargugnani! Do you have an example of a website that is giving you this error? 🙂

**Comment by ash-jc-allen** [comment]
Ahhh yeah! In that case, yeah I'd be open to any PRs that ignore any `<link>` tags that don't have the `href` set 🙂

**Comment by ash-jc-allen** [comment]
Hey @tushargugnani! Thanks to a bug fix by @philipsorensen, this should now be fixed in v3.4.1 😄

Release notes: https://github.com/ash-jc-allen/favicon-fetcher/releases/tag/v3.4.1
