### ISSUE TITLE
Possibility to convert ico to png image

### ISSUE THREAD

**Issue by marispro** [ash-jc-allen/favicon-fetcher#9]
Hello,

just idea that would be nice to have image file to display on html page. Or is it possible already somehow?

**Comment by ash-jc-allen** [comment]
Hey @marispro!

Unfortunately, there isn't any functionality included in this package to convert .ico files to .png.

But, as far as I'm aware, I think most modern browsers now can display .ico files in `<img>` elements 😄

**Comment by marispro** [comment]
@ash-jc-allen  Thats good to know, browsers really displaying ico file, it solves for now.  Thanks :)
